### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/department#50]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] crm_department
- [ ] purchase_department
- [ ] analytic_base_department - ~~https://github.com/OCA/department/pull/56~~ https://github.com/OCA/project/pull/170
- [ ] project_task_department - ~~https://github.com/OCA/department/pull/55~~ https://github.com/OCA/project/pull/173
- [ ] sale_department
- [ ] hr_timesheet_department
- [ ] framework_agreement_department
- [ ] project_department - ~~https://github.com/OCA/department/pull/53~~ https://github.com/OCA/project/pull/171
- [ ] purchase_requisition_department
- [ ] invoice_department
- [ ] project_issue_department
- [ ] analytic_department - ~~https://github.com/OCA/department/pull/54~~ https://github.com/OCA/project/pull/172

**Comment by dreispt** [comment]
Following #40, IMO these modules should be moved to other repos, and 9.0 is a great time for this.
It would be nice to post a recipe to aid in that. I'll try to find some time to do that.

**Comment by dreispt** [comment]
This repository was discontinued, and the modules moved to the related repositories (OCA/project, OCA/crm, etc). Discussion in the contributors ML:https://odoo-community.org/groups/contributors-15/contributors-31944

I'm performing the PRs to move the 8.0 branch.
I won't move the legacy 7.0 and 6.1 branches, and the should be maintained here.
Branch 9.0 should be removed.

**Comment by pedrobaeza** [comment]
OK, but I think this shouldn't be done in a stable OCA version. For v9, I will see it correct, but personally I'm not a user of these modules, so I won't block this.

**Comment by dreispt** [comment]
From the effort point of view, that sounds a good idea. I think I'll follow that path.

**Comment by dreispt** [comment]
@pedrobaeza  Shall we delete branch 9.0 then?

**Comment by pedrobaeza** [comment]
Yeah, I think so

**Comment by dreispt** [comment]
I will delete...

**Comment by pedrobaeza** [comment]
Closing as well
