### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/department#58]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] analytic_base_department
- [ ] analytic_department
- [ ] crm_department
- [ ] framework_agreement_department
- [ ] hr_timesheet_department
- [ ] invoice_department
- [ ] project_department
- [ ] project_issue_department
- [ ] project_task_department
- [ ] purchase_department
- [ ] purchase_requisition_department
- [ ] sale_department

**Comment by dreispt** [comment]
@pedrobaeza This repo is deprecated. We should delete branch 8.0 and 10.0. See #50.
At the time of that discussion I couldn't do it myself, but now I can.

**Comment by pedrobaeza** [comment]
OK, closing

**Comment by dreispt** [comment]
Thanks!
